### PR TITLE
Add Higher Lower Game

### PR DESCRIPTION
**Pull request by ckravig**
I added this pretty sick javascript game I made in high school.

### CODE REVIEW

**Comment by TorryX2** [comment]
Creative idea. Nicely done.

**Review by Torry-Early — APPROVED** [review]
Looks good. Cool idea.

**Comment by dmgegare** [comment]
Looks good to me

**Review by dmgegare — APPROVED** [review]
I approve

**Review by nahoczki — APPROVED** [review]

**Pull request merged**
