### PR TITLE
Edited README file

### PR DESCRIPTION
**Pull request by kyleweiher1**
Punctuation addition

### CODE REVIEW

**Review by lillaschool — APPROVED** [review]
Good job Kyle. Love the README you changed.

**Comment by KamilBharvani** [comment]
Good Job Kyle. Will message you on teams when I have questions.

**Comment by JoseGiles98** [comment]
This looks alright. Keep up the good work!

**Review by KamilBharvani — APPROVED** [review]
Good Job Kyle!

**Review by Tersan06 — APPROVED** [review]
Good job

**Review by nahoczki — APPROVED** [review]

**Pull request merged**
