### PR TITLE
Added new line to index.html for assignment 2

### PR DESCRIPTION
**Pull request by bmarcinkus**
Added new line to html file.

### CODE REVIEW

**Comment by vargasf** [comment]
Great job :)

**Review by jaredmai — APPROVED** [review]
This is some next level programming! Great Job!

**Review by JeremyGlod — APPROVED** [review]
git outta here with your puns 🤣

**Review by ckravig — APPROVED** [review]
Nice pun... 

+10 Social Points

**Review by nahoczki — APPROVED** [review]

**Pull request merged**
